classes:
- service.git.client
- system.linux.system.single
- system.openssh.client.workshop
- system.salt.master.single
- system.salt.master.formula.dev.graphite
- system.salt.master.formula.dev.linux
- system.salt.master.formula.dev.openstack_core
- system.salt.master.formula.dev.saltstack
- system.salt.master.formula.dev.sensu
- system.salt.master.formula.dev.heka
- system.reclass.storage.salt
- system.reclass.storage.system.openstack_dvr_single
parameters:
  _param:
    reclass_data_repository: "https://github.com/tcpcloud/workshop-salt-model.git"
    reclass_data_revision: openstack-dvr
    salt_master_environment_repository: "https://github.com/tcpcloud"
    salt_master_environment_revision: master
    reclass_config_master: 10.10.10.200
    single_address: 10.10.10.200
    salt_master_host: 127.0.0.1
    salt_master_base_environment: dev
    rabbitmq_monitor_password: password
    sensu_message_queue_host: 10.10.10.200
    collectd_backend_carbon_host: 10.10.10.200
    collectd_backend_carbon_port: 2013
  linux:
    system:
      name: config
      domain: openstack-dvr.local
  salt:
    master:
      accept_policy: open_mode
      source:
        engine: pip
        version: 2016.3.0rc2
    minion:
      source:
        engine: pip
        version: 2016.3.0rc2

